### ISSUE TITLE
incorrect import with pnpm ui add xxxx

### ISSUE THREAD

**Issue by hossdar** [codersaadi/turborepo-shadcn#1]
First, many thanks for the awesome repo.

Just a small bug so far when adding a new shad-cn component with ```pnpm ui add card```, 
The imported card.tsx will have the wrong  ```import { cn } from "@repo/lib/utils"```
rather than the correct  ```import { cn } from "@repo/ui/lib/utils"```

Thank you once more, and please consider adding ```input-otp```, I cannot get it built with React 19 with this repo!

**Comment by codersaadi** [comment]
> First, many thanks for the awesome repo.
> 
> Just a small bug so far when adding a new shad-cn component with `pnpm ui add card`, The imported card.tsx will have the wrong `import { cn } from "@repo/lib/utils"` rather than the correct `import { cn } from "@repo/ui/lib/utils"`
> 
> Thank you once more, and please consider adding `input-otp`, I cannot get it built with React 19 with this repo!

fixed, 
the path alias was @repo/ui  but shadcn expects  directories after / like @ui/lib --> lib should be a directory , and @repo/ui was the the name and ui was not a directory , so i have changed it , 
from '@repo/ui'  to 'repo-ui' everywhere.
